# Basic operation

In [1]:
import numpy as np

In [2]:
a = np.array([2,5,3,9])
a
a -2

array([0, 3, 1, 7])

In [3]:
b = np.array([2,5,7,8])
a*b

array([ 4, 25, 21, 72])

In [4]:
c = np.ones((3,3))
c

# array multiplication
c*c

# matrix multiplication
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [5]:
a

array([2, 5, 3, 9])

In [6]:
b

array([2, 5, 7, 8])

In [7]:
a == b

array([ True,  True, False, False])

In [10]:
print (a)
np.std(a)

[2 5 3 9]


2.680951323690902